### ISSUE TITLE
Optimize CNS Address Lookups

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#130]
Instead of making a separate Graph call for each address to see what CNS names they own, create a GraphQL query that will look up all required addresses at once and return them in a single request. Refactor the app to "reverse resolve" CNS names in this way on the receive page, AFTER first attempting ENS resolution, ONLY for addresses that don't already have an ENS result.

**Comment by mds1** [comment]
There's now a contract that lets you batch lookup ENS reverse records, explained [here](https://medium.com/the-ethereum-name-service/integrate-ens-reverse-record-into-your-dapp-to-show-ownership-and-participation-of-your-users-882a4703fee2). So this issue can more generally be to first try a batch reverse lookup of address to ENS, then for the ones with no ENS, fall back to batch CNS lookup.

As an alternative to the ENS reverse record contract, we may just want to use the Multicall contract for ENS reverse lookup, to keep it generic, since we already use that to fetch user token balances

**Comment by mds1** [comment]
We now look up CNS names uses the Resolution library, so going to close this
