### ISSUE TITLE
Better Diagram For REAME and Dev Docs

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#215]
We need a technical diagram laying out the various components of Umbra and how they interact. This can be used in the README and in technical documentation.

**Comment by garyghayrat** [comment]
![Image](https://user-images.githubusercontent.com/61768337/178278643-99d066e6-d012-46d5-a81d-b411d049aeed.png)

Adding in what we discussed last.

**Comment by garyghayrat** [comment]
@mds1 I know you had feedback. We can continue the discussion here.

**Comment by garyghayrat** [comment]
<img width="893" alt="Update" src="https://user-images.githubusercontent.com/61768337/180546826-e6ce0c75-4484-4ddf-847f-a9849c3fec2e.png">
@mds1 How does this look?

**Comment by mds1** [comment]
I like it! Only small comments now:
- You could probably even make the "with/without umbra" even bigger
- The Umbra logo in the top right of the bottom pane feels kinda arbitrarily placed, though I get what you're doing. I think we can remove that since we have the logo elsewhere in the bottom pane.
- The bottom left says solid arrow is an on-chain tx, but that's not exactly true since the first two arrows in the bottom pane are really one tx. Maybe we put a dotted box labeled "first transaction" and "second transaction" around the arrows, if that makes sense?

**Comment by garyghayrat** [comment]
![edit](https://user-images.githubusercontent.com/61768337/181103425-f4439266-8d12-449d-a074-63fc2723f388.png)
How about this? Thought dotted boxes might make it look too busy

**Comment by mds1** [comment]
Maybe we just remove the "on-chain tx" legend and put the arrow back? The "no arrow" line is pretty subtle / technically it's all part of the first transaction. Or what if we make it one giant arrow that goes behind that Umbra circle, and give the Umbra circle some transparency so you can see the arrow behind it?

Either way I'm being nitpicky haha, this is pretty much good to ship

**Comment by garyghayrat** [comment]
![screenshot](https://user-images.githubusercontent.com/61768337/182882741-199588d5-0253-47e6-8ca0-f9ef98a1e89e.png)
Your feedback def has made it much better. Any other feedback @apbendi before shipping to the github README and maybe underneath one of the FAQ questions?

**Comment by apbendi** [comment]
closed by #376
