### ISSUE TITLE
Add Payload Extension To Encrypted Announcement

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#30]
### Proposal

Require a standard payload of data be included, at a standard position, in the message that is encrypted and announced on chain. The size of the payload should be such that it result in exactly 32 additional bytes being added to the ciphertext, requiring one additional `bytes32` parameter included in the contract methods & `Announcement` event.

### But Why?

Flexibility for developers building on top of the protocol. It would enable them to identify certain stealth payments as pertaining to their application, and encode some additional metadata about the payment.

Example 1: A developer builds a Tornado-cash like mixer with Umbra. By placing an identifier in payload extension, they can filter stealth payments for a given user to only those relevant for the mixer application.

Example 2: A developer builds a crypto Invoicing application using Umbra, embedding a unique foreign key identifier of the invoice being paid in the payload extension.

**Comment by mds1** [comment]
One consideration here is that this will reduce the size of the anonymity set. For Example 1 this is inevitable since payment amounts would be restricted to a fixed set of values, but this doesn't have to be happen for the app in Example 2.

You'd probably want to set a default payload value that Umbra will use, and let application developers optionally override it with their own app-specific value (and of course make sure they are aware of the tradeoffs)

**Comment by apbendi** [comment]
> One consideration here is that this will reduce the size of the anonymity set.

How so? To clarify, my thinking is this would be concatenated with the secret **prior** to encryption.

**Comment by mds1** [comment]
Ah I misunderstood. I thought you meant the developer would choose an extra parameter to directly emit (unencrypted) with the Announcement event, with part of the intent being to reduce the scan time for their users.

**Comment by mds1** [comment]
Closed by #61 and #58
