### ISSUE TITLE
bug: Users cannot switch wallets without manually clearing local storage

### ISSUE THREAD

**Issue by davidlaprade** [ScopeLift/umbra-protocol#315]
Once you've connected to the app with a wallet, we remember your wallet app choice via a local storage variable. Then, whenever you return, we immediately attempt to reconnect with that wallet app. If you refuse to connect b/c you want to use another app, you just get this error:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/7997618/160871431-e6c6a5fd-3395-49cb-9518-3b145184191e.png">

The error is fine, but doesn't provide an option to change wallets. We should add a button that clears the local storage var and pops open the wallet select modal:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/7997618/160871798-bce5010c-1220-40f3-be00-11536b2f5455.png">

**Comment by mds1** [comment]
I think we should update the address/avatar so that when clicked it shows something similar to what Uniswap does as shown below. All those features lgtm (except we don't need transaction history)

<img width="447" alt="image" src="https://user-images.githubusercontent.com/17163988/186470049-97339dc1-5233-4262-b71d-09cb8f55c6a6.png">

**Comment by alexkeating** [comment]
Once #395 Is merged I can pick this up and replace the the connect button with Onboards account center
