### ISSUE TITLE
Update `lookupRecipient` to use multicall

### ISSUE THREAD

**Issue by garyghayrat** [ScopeLift/umbra-protocol#519]
We should also consider a tracking issue to change these lookups to a single multicall for even better performance and less RPC usage

_Originally posted by @mds1 in https://github.com/ScopeLift/umbra-protocol/pull/491#discussion_r1201062469_

**Comment by alexkeating** [comment]
I don't know if this is worth the performance increase @mds1. There is a lot going on under `lookupRecipient`, and I don't think it lends itself to a single multicall.

**Comment by mds1** [comment]
Most recipient lookups are just to the stealth key registry, so those are easy to batch with a call to the multicall contract. The rest can't be batched that way because they're RPC calls to get e.g. tx data from the node. You could use JSON RPC batching for that (viem supports this, not sure about ethers) but not all RPC providers support it.

I suspect we won't get big performance gains compared to dispatching all promises simultaneously and using `Promise.all`, but it will save RPC usage if that's a concern.
