### ISSUE TITLE
Do not automatically scan receivces in advanced mode

### ISSUE THREAD

**Issue by alexkeating** [ScopeLift/umbra-protocol#522]
Once a users signs on the receive page when they navigate back to the receive page the receive table will automatically scan.

_Originally posted by @apbendi in https://github.com/ScopeLift/umbra-protocol/pull/520#discussion_r1206975093_

**Comment by alexkeating** [comment]
- I have looked into this and the tricky thing is how do we stop processing results when a user requests a subset of blocks. My first instinct is to move the loading into a separate page rather than have it embedded in the `AccountReceive` page, but open to other suggestions @mds1 @apbendi

**Comment by mds1** [comment]
Hmm I think there might be a misunderstanding on the scope here? 

> how do we stop processing results when a user requests a subset of blocks.

This issue isn't for trying to stop processing results after some amount of blocks. Instead it's to fix the following:
- User signs message on send page or setup page
- App now has their keys in memory
- User visits receive page, and since the keys are in memory it automatically starts scanning.

Instead for the last bullet, there should be a button to click that initiates scanning, that way in advanced mode settings can be configured before scanning

**Comment by alexkeating** [comment]
Cool, yes I think that is achievable. I was trying to implement the mocks @apbendi made in the thread linked in the description rather than preventing the automatic scans
