### ISSUE TITLE
Placeholder: Pass Through ETH

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#55]

**Comment by apbendi** [comment]
Hey @mds1, curious to get your take on this feature. Is it something we want to include in V1, or should we leave it on the cutting room floor? As a reminder, the idea here was we'd allow a sender to include a small amount of ETH with their token transfer which would go straight to the stealth address, so the receiver could use that ETH to pay for gas to withdraw the tokens.

**Comment by mds1** [comment]
> we'd allow a sender to include a small amount of ETH with their token transfer which would go straight to the stealth address

So this adds a third "fund flow", where we'd now have three ways to send funds:
1. ETH to stealth address
2. Tokens to contract, withdraw with meta-transaction
3. Tokens + ETH to stealth address, normal token transfer to withdraw (i.e. don't need `Umbra.sol`)


If so, I think this addition of a third fund flow adds some complexity and complicates UX (which it seems is already confusing enough for users), so I'd learn towards not including this feature for now. Then you have to figure out how to handle the case where not enough ETH was sent. Additionally, Tornado requires relayers and I don't think that's been a blocker to usage in any way

OTOH, we could implement this as follows, which I think is simpler and preferable:
1. ETH to stealth address
2. Tokens to contract, withdraw with meta-transaction
3. Tokens to contract, ETH to stealth address, normal withdraw via `Umbra.withdrawToken()`

But even this still complicates the UX/receive table by a decent amount though:
- Do we assume the user wants to use that ETH for withdrawal, as opposed to a meta-transaction? Probably ok to assume this, but it may not always be true
- Do we assume leftover ETH after withdrawal should be swept to same address as the token? Probably don't want to do this due to #37 
- How to handle case where not enough ETH was sent?

**Comment by apbendi** [comment]
Agree this adds complexity to the UX, and additionally it can be done external to the core protocol via a batching contract, or just via multiple transactions. Closing.
