### ISSUE TITLE
Discussion: Protocol Spec & Definitions

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#6]
Let's establish some definitions. Spitballing here, feel free to 

Q: What is "The Umbra Protocol"? 
A: The Umbra protocol is a set of rules which define an interoperable shadow address standard.

Q: What is in The Umbra Protocol
A: Off the top of my head, it would have to define:
 * Which encryption algorithms are used
 * ENS Text record key
 * Standard message to be signed and stored in the ENS record (salt?)
 * How to format and encrypt announcement data
 * A smart contract where encrypted announcements are published
 * Rules (encoded in the smart contract) on announcing, for example, should an announcement require a small fee payment to prevent spam?

Am I missing anything here for the core protocol?

This library should make it very easy to interact with the protocol, meaning it should provide easy helper functionality for:

* Publishing a signed message to ENS at the appropriate Text record
* Checking if a given ENS name has published an Umbra PK
* Sending a payment to given ENS name, steps:
  1. Find the Text record
  2. Recover public key
  3. Generate random number
  4. User random number to create a new address
  5. Submit payment to Umbra contract
* Checking for payments made to a given ENS name the user controls
 1. Scan & attempt to decrypt all announcements
 2. Identify applicable announcements and extract the random data used
 3. Generate the address + private key

What am I missing. Is this all making sense?

Now that I'm thinking about thisI'm actually wondering if we should rename (again!) this repo, as it doesn't constitute the protocol, but instead represents a library for interacting with a protocol. Like you wouldn't hame a library for interacting with IMAP, IMAP. Or if you did, it would make conversations very difficult. Maybe something like `umbra-core`?

**Comment by mds1** [comment]
> Am I missing anything here for the core protocol?

The only other thing I can think of is specifying how the funds are sent. I'm not sure if this should be part of the main protocol, but it does change how funds are accessed so it might be worth including. 

I think there's two main approaches.
1. Send funds directly to the computed EOA address
2. If we assume the sender calls a function on the Umbra contract call to atomically publish the random number `r` and transfer funds, then we can either: 
    1. Cheaply deploy a minimal proxy contract during that transaction, send funds to that contract, and the contract only lets the funds be withdrawn by the computed address.
    2. Use CREATE2 to send funds to some precomputed address and deploy the contract only upon withdrawal of funds.

The benefits of the second set of options are:
- It removes the need for the recipient to have ETH to withdraw, and they'd use the GSN so gas costs can just be paid for using whatever token the recipient was paid in.
- It allows recipients to specify what token they want to be paid in, so the owner can pay in any token and the receiver can have it automatically converted to DAI, ETH, etc.

> What am I missing. Is this all making sense?

Makes sense! Probably good to write up a spec somewhere for it (where? maybe as an EIP?). The "Sending a payment to given ENS name" is just missing the step to encrypt and send the random number, though that's kind of implied by step v.

At first I was thinking we don't need a contract, and can just send `r` to some arbitrary address. But a contract would probably be good because we can atomically log the `r` as an event or save it in storage, then send the transaction, so it mitigates the issue of the random number not getting delivered to the recipient.

> Now that I'm thinking about thisI'm actually wondering if we should rename (again!) this repo

Yea that's probably a good idea. Either `umbra-core` or `umbra-js` is good with me. No strong preference here!

**Comment by apbendi** [comment]
> If we assume the sender calls a function on the Umbra contract call to atomically publish the random number r and transfer funds, then we can either

Yes, this is what I was thinking. But I had not considered paying to a contract in either of the forms you list below. I had simply thought the umbra protocol contract would forward the funds to the generated EOA. I'm not opposed to the use of a contract recipient, I just want to understand what the benefits are.

> Cheaply deploy a minimal proxy contract during that transaction, send funds to that contract, and the contract only lets the funds be withdrawn by the computed address.

As a baseline, what does this option provide over simply paying the computed EOA? Just trying to understand why we'd even consider it.

> Use CREATE2 to send funds to some precomputed address and deploy the contract only upon withdrawal of funds.

This is interesting. Can you expand on how this would allow us to use GSN? My understanding with GSN is _someone_ still has to pay the gas. Who would that be in our usecase?

Also, with regards to token swaps between payer and receiver, the idea would be the contract deployed upon withdrawl would use Uniswap or something similar to do the conversion? I guess one issue with that is the exchange rate can float significantly between when the payer make a payment and whenever the payee withdraws.

Also, I'm wondering if this functionality would be part of the core protocol, or a layer up. Is there someway the protocol can be flexible to allow uses like this, but without building them into the base itself?

**Comment by mds1** [comment]
I think there are two main benefits to supporting the ability to send to contracts:
- Receiver can customize rules, such as Uniswap (yea, exchange rate could fluctuate though, haven't thought about the details much—just kind of brainstorming) or entering a chosen destination address when calling the contract's withdraw function. Withdrawal address is nice because of the reason below.
- Receiving to a contract enables GSN support. The "someone" that has to pay for gas would just be the recipient—GSN is commonly used in cases where a company pays for gas on behalf of its users. But you can also use it so that users can [pay gas costs in tokens](https://docs.opengsn.org/gsn-provider/gsn-faq.html#who_is_paying_the_gas).
    - This also improves UX because if a user uses Umbra frequently, they will have many different receiving addresses. If they are EOAs, it is tedious to fund each EOA with ETH for gas to withdraw funds, then afterwards withdrawing leftover ETH/dust. With GSN + create2, they can use a meta-tx sent from the stealth EOA to withdraw straight to an arbitrary address, such as an exchange account, cold storage address, etc.

> Also, I'm wondering if this functionality would be part of the core protocol, or a layer up. Is there someway the protocol can be flexible to allow uses like this, but without building them into the base itself?

What about something like this, which would be part of the protocol: When a user first links their pubic key to their ENS address, they also have the option to link bytecode to that address. This is the bytecode used for their receiving contract. Then in our umbra contract, the sender calls a function similar to this:

```solidity
function send(/* inputs here */) external {
  // 1. Save encrypted random value
  // Do stuff...
  // 2. Look up public key and bytecode associated with specified ENS address
  // Do stuff...
  // 3. Transfer the funds
  if (bytecode.length > 0) {
    // If bytecode specified by recipient, use create2 and send to deterministic address
  } else { 
    // Otherwise, use transferFrom to send funds directly to computed EOA
}
```
