### ISSUE TITLE
Upgrade to Latest Unstoppable Library After Deprecating Ropsten

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#88]
Per https://github.com/unstoppabledomains/resolution/issues/112, we've pinned ourselves to an older version of UD library due to a breaking change in v1.10.

It seems that once we've deployed the Phase 1 upgrade to Rinkeby, and deprecated our support for the original Ropsten testnet version, we should be able to upgrade to the latest version without issue.

**Comment by mds1** [comment]
As part of this issue, we should also add CNS support back to `umbra-js` and the frontend. Support was removed since I'm not yet sure of how to support two public keys (details in #29) for CNS. Rough spec for CNS integration:

- In `umbra-js`, `cns.setPublicKeys()` should have the same interface as `ens.setPublicKeys()`. Ideally it should also compress the public keys before storing them on chain to reduce gas costs
- In `umbra-js`, `cns.getPublicKeys` should have the same interface as `ens.getPublicKeys()`
- The `frontend` folder uses the ethers.js method `lookupAddress` to look for an ENS name associated with the address of the connected wallet. These should be placed with a new method that looks for both an ENS and CNS name. Locations where `lookupAddress` is currently used:
    - In `frontend/src/store/wallet.ts`, the `setProvider` method is called after a user connects their wallet 
    - In `frontend/src/components/AccountReceiveTable.vue` we use this to format addresses from senders
    - Open question: If an address has an associated ENS and CNS name, which should we show?

For reference the ENS contract currently used to store the public keys is [here](https://github.com/ensdomains/resolvers/pull/41)

cc @mvlabat for help/guidance on implementing these changes!

**Comment by mvlabat** [comment]
> Open question: If an address has an associated ENS and CNS name, which should we show?

@mds1 I can add as of now CNS doesn't support reverse resolution so it's not possible to look up a CNS name by an Ethereum address. We'll want to support this in future, but I guess solving the UI problem can be postponed.

But if I'd consider it now, I think it could be solved the following way:
- If a user has both ENS and CNS domains associated with an Eth address, but a public key is configured only for one, we can show just the domain it's configured for
- If a public key is configured for both:
  - If they are not equal, a user should choose between the two
  - If they are equal, we can probably show both domains? I'm not sure there's a way to make it pretty in the UI. Otherwise, we can always make the user choose as if they are not equal

**Comment by mds1** [comment]
Got it, didn't realize reverse resolution isn't supported for now. And I'd say, yes, there's a few things we'd love your help with!

1. Given that reverse resolution isn't supported, how can the frontend detect if a user already has a CNS name they can use?

2. In the discussion in https://github.com/unstoppabledomains/resolution/issues/112#issuecomment-763701669, my impression was that after migrating to Rinkeby we'd be able to update to the latest version of the Resolution library, though I'm not sure what exactly we need to do/change to support this

3. How can we define the `setPublicKeys()` and `getPublicKeys()` methods of `cns.ts` to support #29? If you look at the ENS approach, you'll see we used a custom resolver to support this, since that allows us to store all the public key data with just 1 transaction and 2 storage slots. Ideally CNS users would want the same functionality to keep setup gas costs down, so is a similar custom contract needed for CNS?

**Comment by mds1** [comment]
Hey @mvlabat, just wanted to follow up on this—thanks! 🙂

**Comment by mvlabat** [comment]
Hi @mds1, sorry for the delayed answer.

1. There's no easy way to do that via the blockchain directly. But our team has recently developed thegraph integration, which allows getting all domains of an owner: 

```graphql
{
  domains(where: {owner: "LOWERCASE_ADDRESS"}) {
    name
  }
}
```
While it doesn't indicate a main owner's domain, I guess picking the first domain, for which `crypto.ETH.address` matches an owner address, can be good enough.

2. It should just work if you remove this line from the constructor arguments: https://github.com/ScopeLift/umbra-protocol/blob/1cbd27d2cf2217fe91f07d1abfc1e80f74a59ee7/umbra-js/src/classes/DomainService.ts#L25

3. It's a good question. We try to avoid custom setters and getters for domain records. Adding support for Umbra public keys in such a way would mean that besides setting actual records a user would also need to set a custom resolver first. I don't have the exact numbers, but I guess that setting a new resolver AND setting public keys in an optimized manner will cost more than just setting two hex-encoded public keys. To make matters worse, if we are setting a custom resolver, we'll likely want to migrate all user's records from the old resolver, which will increase gas cost drastically.

In terms of setting several records at once, we do have a function for that: https://github.com/unstoppabledomains/dot-crypto/blob/master/contracts/Resolver.sol#L170

So at least it won't be as bad as sending a transaction per each record.

**If we decide to use the existing UD resolver smart contract:**

As for the record keys themselves, I believe that we had `crypto.ETH.signature-v0` before. Do you want to store raw public keys now instead of signatures? I would personally suggest the following keys (but I'll also ask my team about them):

```
crypto.ETH.stealth.generation
crypto.ETH.stealth.encryption
```

But feel free to suggest any other format!

**Comment by mds1** [comment]
Thanks for the details!

1. This seems doable as a solution. I'm actually not too familiar with The Graph, so if you have a sample JavaScript query to share that we can use from the frontend that would be appreciated! If not, no worries—I'll figure it out 

2. Great, I'll give this a try

3. This approach works! As you've noticed we changed from storing signatures to compressed public keys, and have renamed them to "spending" and "viewing" keys. So unless you hear otherwise from the team we'll store them as

```
crypto.ETH.stealth.spendingPublicKey
crypto.ETH.stealth.viewingPublicKey
```

**Comment by mvlabat** [comment]
Yeah, no problem:

```js
// Url for Rinkeby: https://api.thegraph.com/subgraphs/name/unstoppable-domains-integrations/dot-crypto-rinkeby-registry
const res = await fetch('https://api.thegraph.com/subgraphs/name/unstoppable-domains-integrations/dot-crypto-registry', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    variables: {
      owner: '0x87348226e747Df4CFF2b1B1e38A528df405cCD5C'.toLowerCase(),
    },
    query: `query domainsOfOwner($owner: String!) {
  domains(where: {owner: $owner}) {
    name
  }
}`,
  }),
}).then(res => res.json());
```

The response would be:
```js
{
  "data": {
    "domains": [
      {
        "name": "reseller-test-udtesting-260581373338.crypto"
      },
      {
        "name": "reseller-test-udtesting-482542536022.crypto"
      },
      {
        "name": "mvlabat.crypto"
      },
      {
        "name": "unstoppablelizard.crypto"
      },
      // and 8 more domains
    ]
  }
}
```


Thanks for the clarification about the keys! Once I'll discuss it with the team, I'll let you know.

**Comment by mvlabat** [comment]
I've got an update about the keys. We want to suggest the following ones:
```
crypto.ETH.umbra.spending_public_key
crypto.ETH.umbra.viewing_public_key
```

Let me know what you think. :)

**Comment by mds1** [comment]
You got it, we'll use those two keys! And thank you for the JS snippet as well. Should have enough to finish the CNS integration now, thanks!

**Comment by mds1** [comment]
Hey @mvlabat, The Graph query is working great! Question on setting the keys though. Right now I'm getting `ResolutionError: Domain 0xb523f834041c2aa484ca5f422d13e91a72ac459f925e26de7d63381bc26795f6 is not supported`, where that hex string is the namehash of `udtestdev-msolomon.crypto`, and I own that domain on Rinkeby

This error is thrown when I call `await cnsResolver.set('crypto.ETH.umbra.spending_public_key', spendingPublicKey, domainNamehash);`

Any guidance on how to resolve this is appreciated! Here is a link to the specific method I'm using to set it: https://github.com/ScopeLift/umbra-protocol/blob/b4165f92eb4f5c3e088ca652a5bd571e77ab0bee/umbra-js/src/classes/DomainService.ts#L51-L64

------------------------

Also, is there a way to set both records in one transaction, or are two transactions needed?

**Comment by mvlabat** [comment]
Hey @mds1, it's great to hear!
I believe that you have an error in this line:
https://github.com/ScopeLift/umbra-protocol/blob/b4165f92eb4f5c3e088ca652a5bd571e77ab0bee/umbra-js/src/utils/cns.ts#L81

Just pass a domain name there (not a hash).

As for setting several keys at once, you can use the following function:
https://github.com/unstoppabledomains/dot-crypto/blob/14a25a597b645040a2c59cb403489149b4d3ee0e/contracts/Resolver.sol#L170-L176

**Comment by mds1** [comment]
> As for setting several keys at once, you can use the following function:

Ah thank you, I saw `getMany` in the docs so thought there must be a setter equivalent, but missed this!

> Just pass a domain name there (not a hash).

Oops did not realized that! Now this errors with `ResolutionError: Domain udtestdev-msolomon.crypto is not registered`.

I know it's registered because The Graph query successfully finds the domain, so I suspect it may not be looking on the right network? We are initializing the resolution library with a Rinkeby Ethers provider in our `DomainService` class, using:

```
this.udResolution = new Resolution({
    blockchain: {
      cns: {
        provider: Eip1993Factories.fromEthersProvider(provider),
      },
    },
  });
```

**Comment by mvlabat** [comment]
Ah, sorry, we don't auto-detect the network yet. I didn't have a chance to test it in your project, but I believe once you pass
```
cns: {
  provider: Eip1993Factories.fromEthersProvider(ethersProvider),
  network: 'rinkeby',
},
```
it should work.

**Comment by mds1** [comment]
Perfect, yep that did the trick. Thanks a lot! Everything seems to be working now, so I'll have a PR that adds back the CNS functionality soon
